package Projects;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: ChangesState <br>
 * @version generated on Mon Dec 04 20:34:44 COT 2017 by alvarfr
 */

public interface ChangesState extends Changes {

    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate
     */
     
    /**
     * Gets all property values for the Generate property.<p>
     * 
     * @returns a collection of values for the Generate property.
     */
    Collection<? extends Applications> getGenerate();

    /**
     * Checks if the class has a Generate property value.<p>
     * 
     * @return true if there is a Generate property value.
     */
    boolean hasGenerate();

    /**
     * Adds a Generate property value.<p>
     * 
     * @param newGenerate the Generate property value to be added
     */
    void addGenerate(Applications newGenerate);

    /**
     * Removes a Generate property value.<p>
     * 
     * @param oldGenerate the Generate property value to be removed.
     */
    void removeGenerate(Applications oldGenerate);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Input_for
     */
     
    /**
     * Gets all property values for the Input_for property.<p>
     * 
     * @returns a collection of values for the Input_for property.
     */
    Collection<? extends WorkOrders> getInput_for();

    /**
     * Checks if the class has a Input_for property value.<p>
     * 
     * @return true if there is a Input_for property value.
     */
    boolean hasInput_for();

    /**
     * Adds a Input_for property value.<p>
     * 
     * @param newInput_for the Input_for property value to be added
     */
    void addInput_for(WorkOrders newInput_for);

    /**
     * Removes a Input_for property value.<p>
     * 
     * @param oldInput_for the Input_for property value to be removed.
     */
    void removeInput_for(WorkOrders oldInput_for);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modified_By
     */
     
    /**
     * Gets all property values for the Modified_By property.<p>
     * 
     * @returns a collection of values for the Modified_By property.
     */
    Collection<? extends Changes> getModified_By();

    /**
     * Checks if the class has a Modified_By property value.<p>
     * 
     * @return true if there is a Modified_By property value.
     */
    boolean hasModified_By();

    /**
     * Adds a Modified_By property value.<p>
     * 
     * @param newModified_By the Modified_By property value to be added
     */
    void addModified_By(Changes newModified_By);

    /**
     * Removes a Modified_By property value.<p>
     * 
     * @param oldModified_By the Modified_By property value to be removed.
     */
    void removeModified_By(Changes oldModified_By);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modify
     */
     
    /**
     * Gets all property values for the Modify property.<p>
     * 
     * @returns a collection of values for the Modify property.
     */
    Collection<? extends Applications> getModify();

    /**
     * Checks if the class has a Modify property value.<p>
     * 
     * @return true if there is a Modify property value.
     */
    boolean hasModify();

    /**
     * Adds a Modify property value.<p>
     * 
     * @param newModify the Modify property value to be added
     */
    void addModify(Applications newModify);

    /**
     * Removes a Modify property value.<p>
     * 
     * @param oldModify the Modify property value to be removed.
     */
    void removeModify(Applications oldModify);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support
     */
     
    /**
     * Gets all property values for the Support property.<p>
     * 
     * @returns a collection of values for the Support property.
     */
    Collection<? extends Applications> getSupport();

    /**
     * Checks if the class has a Support property value.<p>
     * 
     * @return true if there is a Support property value.
     */
    boolean hasSupport();

    /**
     * Adds a Support property value.<p>
     * 
     * @param newSupport the Support property value to be added
     */
    void addSupport(Applications newSupport);

    /**
     * Removes a Support property value.<p>
     * 
     * @param oldSupport the Support property value to be removed.
     */
    void removeSupport(Applications oldSupport);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support_By
     */
     
    /**
     * Gets all property values for the Support_By property.<p>
     * 
     * @returns a collection of values for the Support_By property.
     */
    Collection<? extends Analyst> getSupport_By();

    /**
     * Checks if the class has a Support_By property value.<p>
     * 
     * @return true if there is a Support_By property value.
     */
    boolean hasSupport_By();

    /**
     * Adds a Support_By property value.<p>
     * 
     * @param newSupport_By the Support_By property value to be added
     */
    void addSupport_By(Analyst newSupport_By);

    /**
     * Removes a Support_By property value.<p>
     * 
     * @param oldSupport_By the Support_By property value to be removed.
     */
    void removeSupport_By(Analyst oldSupport_By);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ApplicationName
     */
     
    /**
     * Gets all property values for the ApplicationName property.<p>
     * 
     * @returns a collection of values for the ApplicationName property.
     */
    Collection<? extends String> getApplicationName();

    /**
     * Checks if the class has a ApplicationName property value.<p>
     * 
     * @return true if there is a ApplicationName property value.
     */
    boolean hasApplicationName();

    /**
     * Adds a ApplicationName property value.<p>
     * 
     * @param newApplicationName the ApplicationName property value to be added
     */
    void addApplicationName(String newApplicationName);

    /**
     * Removes a ApplicationName property value.<p>
     * 
     * @param oldApplicationName the ApplicationName property value to be removed.
     */
    void removeApplicationName(String oldApplicationName);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeId
     */
     
    /**
     * Gets all property values for the ChangeId property.<p>
     * 
     * @returns a collection of values for the ChangeId property.
     */
    Collection<? extends Integer> getChangeId();

    /**
     * Checks if the class has a ChangeId property value.<p>
     * 
     * @return true if there is a ChangeId property value.
     */
    boolean hasChangeId();

    /**
     * Adds a ChangeId property value.<p>
     * 
     * @param newChangeId the ChangeId property value to be added
     */
    void addChangeId(Integer newChangeId);

    /**
     * Removes a ChangeId property value.<p>
     * 
     * @param oldChangeId the ChangeId property value to be removed.
     */
    void removeChangeId(Integer oldChangeId);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeSummary
     */
     
    /**
     * Gets all property values for the ChangeSummary property.<p>
     * 
     * @returns a collection of values for the ChangeSummary property.
     */
    Collection<? extends String> getChangeSummary();

    /**
     * Checks if the class has a ChangeSummary property value.<p>
     * 
     * @return true if there is a ChangeSummary property value.
     */
    boolean hasChangeSummary();

    /**
     * Adds a ChangeSummary property value.<p>
     * 
     * @param newChangeSummary the ChangeSummary property value to be added
     */
    void addChangeSummary(String newChangeSummary);

    /**
     * Removes a ChangeSummary property value.<p>
     * 
     * @param oldChangeSummary the ChangeSummary property value to be removed.
     */
    void removeChangeSummary(String oldChangeSummary);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeType
     */
     
    /**
     * Gets all property values for the ChangeType property.<p>
     * 
     * @returns a collection of values for the ChangeType property.
     */
    Collection<? extends String> getChangeType();

    /**
     * Checks if the class has a ChangeType property value.<p>
     * 
     * @return true if there is a ChangeType property value.
     */
    boolean hasChangeType();

    /**
     * Adds a ChangeType property value.<p>
     * 
     * @param newChangeType the ChangeType property value to be added
     */
    void addChangeType(String newChangeType);

    /**
     * Removes a ChangeType property value.<p>
     * 
     * @param oldChangeType the ChangeType property value to be removed.
     */
    void removeChangeType(String oldChangeType);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Description
     */
     
    /**
     * Gets all property values for the Description property.<p>
     * 
     * @returns a collection of values for the Description property.
     */
    Collection<? extends String> getDescription();

    /**
     * Checks if the class has a Description property value.<p>
     * 
     * @return true if there is a Description property value.
     */
    boolean hasDescription();

    /**
     * Adds a Description property value.<p>
     * 
     * @param newDescription the Description property value to be added
     */
    void addDescription(String newDescription);

    /**
     * Removes a Description property value.<p>
     * 
     * @param oldDescription the Description property value to be removed.
     */
    void removeDescription(String oldDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#EstimatedDeliveryDate
     */
     
    /**
     * Gets all property values for the EstimatedDeliveryDate property.<p>
     * 
     * @returns a collection of values for the EstimatedDeliveryDate property.
     */
    Collection<? extends XMLGregorianCalendar> getEstimatedDeliveryDate();

    /**
     * Checks if the class has a EstimatedDeliveryDate property value.<p>
     * 
     * @return true if there is a EstimatedDeliveryDate property value.
     */
    boolean hasEstimatedDeliveryDate();

    /**
     * Adds a EstimatedDeliveryDate property value.<p>
     * 
     * @param newEstimatedDeliveryDate the EstimatedDeliveryDate property value to be added
     */
    void addEstimatedDeliveryDate(XMLGregorianCalendar newEstimatedDeliveryDate);

    /**
     * Removes a EstimatedDeliveryDate property value.<p>
     * 
     * @param oldEstimatedDeliveryDate the EstimatedDeliveryDate property value to be removed.
     */
    void removeEstimatedDeliveryDate(XMLGregorianCalendar oldEstimatedDeliveryDate);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Id
     */
     
    /**
     * Gets all property values for the Id property.<p>
     * 
     * @returns a collection of values for the Id property.
     */
    Collection<? extends Integer> getId();

    /**
     * Checks if the class has a Id property value.<p>
     * 
     * @return true if there is a Id property value.
     */
    boolean hasId();

    /**
     * Adds a Id property value.<p>
     * 
     * @param newId the Id property value to be added
     */
    void addId(Integer newId);

    /**
     * Removes a Id property value.<p>
     * 
     * @param oldId the Id property value to be removed.
     */
    void removeId(Integer oldId);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#SendDate
     */
     
    /**
     * Gets all property values for the SendDate property.<p>
     * 
     * @returns a collection of values for the SendDate property.
     */
    Collection<? extends XMLGregorianCalendar> getSendDate();

    /**
     * Checks if the class has a SendDate property value.<p>
     * 
     * @return true if there is a SendDate property value.
     */
    boolean hasSendDate();

    /**
     * Adds a SendDate property value.<p>
     * 
     * @param newSendDate the SendDate property value to be added
     */
    void addSendDate(XMLGregorianCalendar newSendDate);

    /**
     * Removes a SendDate property value.<p>
     * 
     * @param oldSendDate the SendDate property value to be removed.
     */
    void removeSendDate(XMLGregorianCalendar oldSendDate);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#State
     */
     
    /**
     * Gets all property values for the State property.<p>
     * 
     * @returns a collection of values for the State property.
     */
    Collection<? extends Boolean> getState();

    /**
     * Checks if the class has a State property value.<p>
     * 
     * @return true if there is a State property value.
     */
    boolean hasState();

    /**
     * Adds a State property value.<p>
     * 
     * @param newState the State property value to be added
     */
    void addState(Boolean newState);

    /**
     * Removes a State property value.<p>
     * 
     * @param oldState the State property value to be removed.
     */
    void removeState(Boolean oldState);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
