package Projects;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Projects <br>
 * @version generated on Mon Dec 04 20:34:44 COT 2017 by alvarfr
 */

public interface Projects extends Applications {

    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Contain
     */
     
    /**
     * Gets all property values for the Contain property.<p>
     * 
     * @returns a collection of values for the Contain property.
     */
    Collection<? extends Tasks> getContain();

    /**
     * Checks if the class has a Contain property value.<p>
     * 
     * @return true if there is a Contain property value.
     */
    boolean hasContain();

    /**
     * Adds a Contain property value.<p>
     * 
     * @param newContain the Contain property value to be added
     */
    void addContain(Tasks newContain);

    /**
     * Removes a Contain property value.<p>
     * 
     * @param oldContain the Contain property value to be removed.
     */
    void removeContain(Tasks oldContain);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate
     */
     
    /**
     * Gets all property values for the Generate property.<p>
     * 
     * @returns a collection of values for the Generate property.
     */
    Collection<? extends Applications> getGenerate();

    /**
     * Checks if the class has a Generate property value.<p>
     * 
     * @return true if there is a Generate property value.
     */
    boolean hasGenerate();

    /**
     * Adds a Generate property value.<p>
     * 
     * @param newGenerate the Generate property value to be added
     */
    void addGenerate(Applications newGenerate);

    /**
     * Removes a Generate property value.<p>
     * 
     * @param oldGenerate the Generate property value to be removed.
     */
    void removeGenerate(Applications oldGenerate);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Input_for
     */
     
    /**
     * Gets all property values for the Input_for property.<p>
     * 
     * @returns a collection of values for the Input_for property.
     */
    Collection<? extends WorkOrders> getInput_for();

    /**
     * Checks if the class has a Input_for property value.<p>
     * 
     * @return true if there is a Input_for property value.
     */
    boolean hasInput_for();

    /**
     * Adds a Input_for property value.<p>
     * 
     * @param newInput_for the Input_for property value to be added
     */
    void addInput_for(WorkOrders newInput_for);

    /**
     * Removes a Input_for property value.<p>
     * 
     * @param oldInput_for the Input_for property value to be removed.
     */
    void removeInput_for(WorkOrders oldInput_for);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modified_By
     */
     
    /**
     * Gets all property values for the Modified_By property.<p>
     * 
     * @returns a collection of values for the Modified_By property.
     */
    Collection<? extends Changes> getModified_By();

    /**
     * Checks if the class has a Modified_By property value.<p>
     * 
     * @return true if there is a Modified_By property value.
     */
    boolean hasModified_By();

    /**
     * Adds a Modified_By property value.<p>
     * 
     * @param newModified_By the Modified_By property value to be added
     */
    void addModified_By(Changes newModified_By);

    /**
     * Removes a Modified_By property value.<p>
     * 
     * @param oldModified_By the Modified_By property value to be removed.
     */
    void removeModified_By(Changes oldModified_By);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support
     */
     
    /**
     * Gets all property values for the Support property.<p>
     * 
     * @returns a collection of values for the Support property.
     */
    Collection<? extends Applications> getSupport();

    /**
     * Checks if the class has a Support property value.<p>
     * 
     * @return true if there is a Support property value.
     */
    boolean hasSupport();

    /**
     * Adds a Support property value.<p>
     * 
     * @param newSupport the Support property value to be added
     */
    void addSupport(Applications newSupport);

    /**
     * Removes a Support property value.<p>
     * 
     * @param oldSupport the Support property value to be removed.
     */
    void removeSupport(Applications oldSupport);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support_By
     */
     
    /**
     * Gets all property values for the Support_By property.<p>
     * 
     * @returns a collection of values for the Support_By property.
     */
    Collection<? extends Analyst> getSupport_By();

    /**
     * Checks if the class has a Support_By property value.<p>
     * 
     * @return true if there is a Support_By property value.
     */
    boolean hasSupport_By();

    /**
     * Adds a Support_By property value.<p>
     * 
     * @param newSupport_By the Support_By property value to be added
     */
    void addSupport_By(Analyst newSupport_By);

    /**
     * Removes a Support_By property value.<p>
     * 
     * @param oldSupport_By the Support_By property value to be removed.
     */
    void removeSupport_By(Analyst oldSupport_By);


    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ApplicationName
     */
     
    /**
     * Gets all property values for the ApplicationName property.<p>
     * 
     * @returns a collection of values for the ApplicationName property.
     */
    Collection<? extends String> getApplicationName();

    /**
     * Checks if the class has a ApplicationName property value.<p>
     * 
     * @return true if there is a ApplicationName property value.
     */
    boolean hasApplicationName();

    /**
     * Adds a ApplicationName property value.<p>
     * 
     * @param newApplicationName the ApplicationName property value to be added
     */
    void addApplicationName(String newApplicationName);

    /**
     * Removes a ApplicationName property value.<p>
     * 
     * @param oldApplicationName the ApplicationName property value to be removed.
     */
    void removeApplicationName(String oldApplicationName);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Description
     */
     
    /**
     * Gets all property values for the Description property.<p>
     * 
     * @returns a collection of values for the Description property.
     */
    Collection<? extends String> getDescription();

    /**
     * Checks if the class has a Description property value.<p>
     * 
     * @return true if there is a Description property value.
     */
    boolean hasDescription();

    /**
     * Adds a Description property value.<p>
     * 
     * @param newDescription the Description property value to be added
     */
    void addDescription(String newDescription);

    /**
     * Removes a Description property value.<p>
     * 
     * @param oldDescription the Description property value to be removed.
     */
    void removeDescription(String oldDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Id
     */
     
    /**
     * Gets all property values for the Id property.<p>
     * 
     * @returns a collection of values for the Id property.
     */
    Collection<? extends Integer> getId();

    /**
     * Checks if the class has a Id property value.<p>
     * 
     * @return true if there is a Id property value.
     */
    boolean hasId();

    /**
     * Adds a Id property value.<p>
     * 
     * @param newId the Id property value to be added
     */
    void addId(Integer newId);

    /**
     * Removes a Id property value.<p>
     * 
     * @param oldId the Id property value to be removed.
     */
    void removeId(Integer oldId);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectFinishDate
     */
     
    /**
     * Gets all property values for the ProjectFinishDate property.<p>
     * 
     * @returns a collection of values for the ProjectFinishDate property.
     */
    Collection<? extends XMLGregorianCalendar> getProjectFinishDate();

    /**
     * Checks if the class has a ProjectFinishDate property value.<p>
     * 
     * @return true if there is a ProjectFinishDate property value.
     */
    boolean hasProjectFinishDate();

    /**
     * Adds a ProjectFinishDate property value.<p>
     * 
     * @param newProjectFinishDate the ProjectFinishDate property value to be added
     */
    void addProjectFinishDate(XMLGregorianCalendar newProjectFinishDate);

    /**
     * Removes a ProjectFinishDate property value.<p>
     * 
     * @param oldProjectFinishDate the ProjectFinishDate property value to be removed.
     */
    void removeProjectFinishDate(XMLGregorianCalendar oldProjectFinishDate);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectId
     */
     
    /**
     * Gets all property values for the ProjectId property.<p>
     * 
     * @returns a collection of values for the ProjectId property.
     */
    Collection<? extends Integer> getProjectId();

    /**
     * Checks if the class has a ProjectId property value.<p>
     * 
     * @return true if there is a ProjectId property value.
     */
    boolean hasProjectId();

    /**
     * Adds a ProjectId property value.<p>
     * 
     * @param newProjectId the ProjectId property value to be added
     */
    void addProjectId(Integer newProjectId);

    /**
     * Removes a ProjectId property value.<p>
     * 
     * @param oldProjectId the ProjectId property value to be removed.
     */
    void removeProjectId(Integer oldProjectId);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectName
     */
     
    /**
     * Gets all property values for the ProjectName property.<p>
     * 
     * @returns a collection of values for the ProjectName property.
     */
    Collection<? extends String> getProjectName();

    /**
     * Checks if the class has a ProjectName property value.<p>
     * 
     * @return true if there is a ProjectName property value.
     */
    boolean hasProjectName();

    /**
     * Adds a ProjectName property value.<p>
     * 
     * @param newProjectName the ProjectName property value to be added
     */
    void addProjectName(String newProjectName);

    /**
     * Removes a ProjectName property value.<p>
     * 
     * @param oldProjectName the ProjectName property value to be removed.
     */
    void removeProjectName(String oldProjectName);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectOwnerName
     */
     
    /**
     * Gets all property values for the ProjectOwnerName property.<p>
     * 
     * @returns a collection of values for the ProjectOwnerName property.
     */
    Collection<? extends String> getProjectOwnerName();

    /**
     * Checks if the class has a ProjectOwnerName property value.<p>
     * 
     * @return true if there is a ProjectOwnerName property value.
     */
    boolean hasProjectOwnerName();

    /**
     * Adds a ProjectOwnerName property value.<p>
     * 
     * @param newProjectOwnerName the ProjectOwnerName property value to be added
     */
    void addProjectOwnerName(String newProjectOwnerName);

    /**
     * Removes a ProjectOwnerName property value.<p>
     * 
     * @param oldProjectOwnerName the ProjectOwnerName property value to be removed.
     */
    void removeProjectOwnerName(String oldProjectOwnerName);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectRemmainingTime
     */
     
    /**
     * Gets all property values for the ProjectRemmainingTime property.<p>
     * 
     * @returns a collection of values for the ProjectRemmainingTime property.
     */
    Collection<? extends Object> getProjectRemmainingTime();

    /**
     * Checks if the class has a ProjectRemmainingTime property value.<p>
     * 
     * @return true if there is a ProjectRemmainingTime property value.
     */
    boolean hasProjectRemmainingTime();

    /**
     * Adds a ProjectRemmainingTime property value.<p>
     * 
     * @param newProjectRemmainingTime the ProjectRemmainingTime property value to be added
     */
    void addProjectRemmainingTime(Object newProjectRemmainingTime);

    /**
     * Removes a ProjectRemmainingTime property value.<p>
     * 
     * @param oldProjectRemmainingTime the ProjectRemmainingTime property value to be removed.
     */
    void removeProjectRemmainingTime(Object oldProjectRemmainingTime);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectStartDate
     */
     
    /**
     * Gets all property values for the ProjectStartDate property.<p>
     * 
     * @returns a collection of values for the ProjectStartDate property.
     */
    Collection<? extends XMLGregorianCalendar> getProjectStartDate();

    /**
     * Checks if the class has a ProjectStartDate property value.<p>
     * 
     * @return true if there is a ProjectStartDate property value.
     */
    boolean hasProjectStartDate();

    /**
     * Adds a ProjectStartDate property value.<p>
     * 
     * @param newProjectStartDate the ProjectStartDate property value to be added
     */
    void addProjectStartDate(XMLGregorianCalendar newProjectStartDate);

    /**
     * Removes a ProjectStartDate property value.<p>
     * 
     * @param oldProjectStartDate the ProjectStartDate property value to be removed.
     */
    void removeProjectStartDate(XMLGregorianCalendar oldProjectStartDate);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectState
     */
     
    /**
     * Gets all property values for the ProjectState property.<p>
     * 
     * @returns a collection of values for the ProjectState property.
     */
    Collection<? extends String> getProjectState();

    /**
     * Checks if the class has a ProjectState property value.<p>
     * 
     * @return true if there is a ProjectState property value.
     */
    boolean hasProjectState();

    /**
     * Adds a ProjectState property value.<p>
     * 
     * @param newProjectState the ProjectState property value to be added
     */
    void addProjectState(String newProjectState);

    /**
     * Removes a ProjectState property value.<p>
     * 
     * @param oldProjectState the ProjectState property value to be removed.
     */
    void removeProjectState(String oldProjectState);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectType
     */
     
    /**
     * Gets all property values for the ProjectType property.<p>
     * 
     * @returns a collection of values for the ProjectType property.
     */
    Collection<? extends String> getProjectType();

    /**
     * Checks if the class has a ProjectType property value.<p>
     * 
     * @return true if there is a ProjectType property value.
     */
    boolean hasProjectType();

    /**
     * Adds a ProjectType property value.<p>
     * 
     * @param newProjectType the ProjectType property value to be added
     */
    void addProjectType(String newProjectType);

    /**
     * Removes a ProjectType property value.<p>
     * 
     * @param oldProjectType the ProjectType property value to be removed.
     */
    void removeProjectType(String oldProjectType);



    /* ***************************************************
     * Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#State
     */
     
    /**
     * Gets all property values for the State property.<p>
     * 
     * @returns a collection of values for the State property.
     */
    Collection<? extends Boolean> getState();

    /**
     * Checks if the class has a State property value.<p>
     * 
     * @return true if there is a State property value.
     */
    boolean hasState();

    /**
     * Adds a State property value.<p>
     * 
     * @param newState the State property value to be added
     */
    void addState(Boolean newState);

    /**
     * Removes a State property value.<p>
     * 
     * @param oldState the State property value to be removed.
     */
    void removeState(Boolean oldState);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
