package Projects;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Dec 04 20:34:43 COT 2017 by alvarfr
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Analyst
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANALYST.<p>
     * 
     */
    public static final OWLClass CLASS_ANALYST = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Analyst"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Applications
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPLICATIONS.<p>
     * 
     */
    public static final OWLClass CLASS_APPLICATIONS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Applications"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Changes
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHANGES.<p>
     * 
     */
    public static final OWLClass CLASS_CHANGES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Changes"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangesState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHANGESSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_CHANGESSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangesState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ClosedChanges
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLOSEDCHANGES.<p>
     * 
     */
    public static final OWLClass CLASS_CLOSEDCHANGES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ClosedChanges"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ClosedIncidents
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLOSEDINCIDENTS.<p>
     * 
     */
    public static final OWLClass CLASS_CLOSEDINCIDENTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ClosedIncidents"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ClosedWorkOrders
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLOSEDWORKORDERS.<p>
     * 
     */
    public static final OWLClass CLASS_CLOSEDWORKORDERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ClosedWorkOrders"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Incidents
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INCIDENTS.<p>
     * 
     */
    public static final OWLClass CLASS_INCIDENTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Incidents"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ManagedChanges
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MANAGEDCHANGES.<p>
     * 
     */
    public static final OWLClass CLASS_MANAGEDCHANGES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ManagedChanges"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#NotScheduledTasks
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOTSCHEDULEDTASKS.<p>
     * 
     */
    public static final OWLClass CLASS_NOTSCHEDULEDTASKS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#NotScheduledTasks"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Projects
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECTS.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Projects"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ScheduledTasks
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHEDULEDTASKS.<p>
     * 
     */
    public static final OWLClass CLASS_SCHEDULEDTASKS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ScheduledTasks"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Tasks
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TASKS.<p>
     * 
     */
    public static final OWLClass CLASS_TASKS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Tasks"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Users
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERS.<p>
     * 
     */
    public static final OWLClass CLASS_USERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Users"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrders
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WORKORDERS.<p>
     * 
     */
    public static final OWLClass CLASS_WORKORDERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrders"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Contain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAIN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Contain"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Contain_By
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAIN_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAIN_BY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Contain_By"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property GENERATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GENERATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate_In
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property GENERATE_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GENERATE_IN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate_In"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Input_for
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INPUT_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INPUT_FOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Input_for"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modified_By
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MODIFIED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MODIFIED_BY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modified_By"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modify
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MODIFY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MODIFY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modify"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Requeriment_Over
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUERIMENT_OVER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUERIMENT_OVER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Requeriment_Over"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUPPORT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUPPORT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support_By
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUPPORT_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUPPORT_BY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support_By"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ApplicationName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property APPLICATIONNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_APPLICATIONNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ApplicationName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeId
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHANGEID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHANGEID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeId"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeSummary
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHANGESUMMARY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHANGESUMMARY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeSummary"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHANGETYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHANGETYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ChangeType"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperEMail
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEVELOPEREMAIL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEVELOPEREMAIL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperEMail"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperId
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEVELOPERID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEVELOPERID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperId"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEVELOPERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEVELOPERNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperPhoneNumber
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEVELOPERPHONENUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEVELOPERPHONENUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperPhoneNumber"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperSurName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEVELOPERSURNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEVELOPERSURNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperSurName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#EstimatedDeliveryDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ESTIMATEDDELIVERYDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ESTIMATEDDELIVERYDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#EstimatedDeliveryDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Id
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Id"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentCreationDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INCIDENTCREATIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INCIDENTCREATIONDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentCreationDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentId
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INCIDENTID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INCIDENTID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentId"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentPriority
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INCIDENTPRIORITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INCIDENTPRIORITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentPriority"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentResolutionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INCIDENTRESOLUTIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INCIDENTRESOLUTIONDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentResolutionDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INCIDENTSTATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INCIDENTSTATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentState"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentSummary
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INCIDENTSUMMARY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INCIDENTSUMMARY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentSummary"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectFinishDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTFINISHDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTFINISHDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectFinishDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectId
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectId"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectOwnerName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTOWNERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTOWNERNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectOwnerName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectRemmainingTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTREMMAININGTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTREMMAININGTIME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectRemmainingTime"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectStartDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTSTARTDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTSTARTDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectStartDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTSTATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTSTATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectState"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PROJECTTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PROJECTTYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectType"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#SendDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SENDDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SENDDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#SendDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#State
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#State"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserArea
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property USERAREA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_USERAREA = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserArea"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserCharge
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property USERCHARGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_USERCHARGE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserCharge"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserEMail
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property USEREMAIL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_USEREMAIL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserEMail"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserId
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property USERID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_USERID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserId"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property USERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_USERNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserPhoneNumber
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property USERPHONENUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_USERPHONENUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserPhoneNumber"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserSurName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property USERSURNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_USERSURNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#UserSurName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderCreationDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORKORDERCREATIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORKORDERCREATIONDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderCreationDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderId
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORKORDERID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORKORDERID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderId"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderPriority
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORKORDERPRIORITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORKORDERPRIORITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderPriority"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderResolutionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORKORDERRESOLUTIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORKORDERRESOLUTIONDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderResolutionDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORKORDERSTATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORKORDERSTATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderState"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderSummary
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORKORDERSUMMARY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORKORDERSUMMARY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#WorkOrderSummary"));


}
