package Projects.impl;

import Projects.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAnalyst <br>
 * @version generated on Mon Dec 04 20:34:44 COT 2017 by alvarfr
 */
public class DefaultAnalyst extends WrappedIndividualImpl implements Analyst {

    public DefaultAnalyst(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate
     */
     
    public Collection<? extends Applications> getGenerate() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_GENERATE,
                                               DefaultApplications.class);
    }

    public boolean hasGenerate() {
	   return !getGenerate().isEmpty();
    }

    public void addGenerate(Applications newGenerate) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_GENERATE,
                                       newGenerate);
    }

    public void removeGenerate(Applications oldGenerate) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_GENERATE,
                                          oldGenerate);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Input_for
     */
     
    public Collection<? extends WorkOrders> getInput_for() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                               DefaultWorkOrders.class);
    }

    public boolean hasInput_for() {
	   return !getInput_for().isEmpty();
    }

    public void addInput_for(WorkOrders newInput_for) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                       newInput_for);
    }

    public void removeInput_for(WorkOrders oldInput_for) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                          oldInput_for);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modified_By
     */
     
    public Collection<? extends Changes> getModified_By() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                               DefaultChanges.class);
    }

    public boolean hasModified_By() {
	   return !getModified_By().isEmpty();
    }

    public void addModified_By(Changes newModified_By) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                       newModified_By);
    }

    public void removeModified_By(Changes oldModified_By) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                          oldModified_By);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support
     */
     
    public Collection<? extends Applications> getSupport() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                               DefaultApplications.class);
    }

    public boolean hasSupport() {
	   return !getSupport().isEmpty();
    }

    public void addSupport(Applications newSupport) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                       newSupport);
    }

    public void removeSupport(Applications oldSupport) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                          oldSupport);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support_By
     */
     
    public Collection<? extends Analyst> getSupport_By() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                               DefaultAnalyst.class);
    }

    public boolean hasSupport_By() {
	   return !getSupport_By().isEmpty();
    }

    public void addSupport_By(Analyst newSupport_By) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                       newSupport_By);
    }

    public void removeSupport_By(Analyst oldSupport_By) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                          oldSupport_By);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ApplicationName
     */
     
    public Collection<? extends String> getApplicationName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, String.class);
    }

    public boolean hasApplicationName() {
		return !getApplicationName().isEmpty();
    }

    public void addApplicationName(String newApplicationName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, newApplicationName);
    }

    public void removeApplicationName(String oldApplicationName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, oldApplicationName);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Description
     */
     
    public Collection<? extends String> getDescription() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, String.class);
    }

    public boolean hasDescription() {
		return !getDescription().isEmpty();
    }

    public void addDescription(String newDescription) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, newDescription);
    }

    public void removeDescription(String oldDescription) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, oldDescription);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperEMail
     */
     
    public Collection<? extends String> getDeveloperEMail() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPEREMAIL, String.class);
    }

    public boolean hasDeveloperEMail() {
		return !getDeveloperEMail().isEmpty();
    }

    public void addDeveloperEMail(String newDeveloperEMail) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPEREMAIL, newDeveloperEMail);
    }

    public void removeDeveloperEMail(String oldDeveloperEMail) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPEREMAIL, oldDeveloperEMail);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperId
     */
     
    public Collection<? extends Integer> getDeveloperId() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERID, Integer.class);
    }

    public boolean hasDeveloperId() {
		return !getDeveloperId().isEmpty();
    }

    public void addDeveloperId(Integer newDeveloperId) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERID, newDeveloperId);
    }

    public void removeDeveloperId(Integer oldDeveloperId) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERID, oldDeveloperId);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperName
     */
     
    public Collection<? extends String> getDeveloperName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERNAME, String.class);
    }

    public boolean hasDeveloperName() {
		return !getDeveloperName().isEmpty();
    }

    public void addDeveloperName(String newDeveloperName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERNAME, newDeveloperName);
    }

    public void removeDeveloperName(String oldDeveloperName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERNAME, oldDeveloperName);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperPhoneNumber
     */
     
    public Collection<? extends Integer> getDeveloperPhoneNumber() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERPHONENUMBER, Integer.class);
    }

    public boolean hasDeveloperPhoneNumber() {
		return !getDeveloperPhoneNumber().isEmpty();
    }

    public void addDeveloperPhoneNumber(Integer newDeveloperPhoneNumber) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERPHONENUMBER, newDeveloperPhoneNumber);
    }

    public void removeDeveloperPhoneNumber(Integer oldDeveloperPhoneNumber) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERPHONENUMBER, oldDeveloperPhoneNumber);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#DeveloperSurName
     */
     
    public Collection<? extends String> getDeveloperSurName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERSURNAME, String.class);
    }

    public boolean hasDeveloperSurName() {
		return !getDeveloperSurName().isEmpty();
    }

    public void addDeveloperSurName(String newDeveloperSurName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERSURNAME, newDeveloperSurName);
    }

    public void removeDeveloperSurName(String oldDeveloperSurName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEVELOPERSURNAME, oldDeveloperSurName);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Id
     */
     
    public Collection<? extends Integer> getId() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, Integer.class);
    }

    public boolean hasId() {
		return !getId().isEmpty();
    }

    public void addId(Integer newId) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, newId);
    }

    public void removeId(Integer oldId) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, oldId);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#State
     */
     
    public Collection<? extends Boolean> getState() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, Boolean.class);
    }

    public boolean hasState() {
		return !getState().isEmpty();
    }

    public void addState(Boolean newState) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, newState);
    }

    public void removeState(Boolean oldState) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, oldState);
    }


}
