package Projects.impl;

import Projects.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultScheduledTasks <br>
 * @version generated on Mon Dec 04 20:34:44 COT 2017 by alvarfr
 */
public class DefaultScheduledTasks extends WrappedIndividualImpl implements ScheduledTasks {

    public DefaultScheduledTasks(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Contain
     */
     
    public Collection<? extends Tasks> getContain() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CONTAIN,
                                               DefaultTasks.class);
    }

    public boolean hasContain() {
	   return !getContain().isEmpty();
    }

    public void addContain(Tasks newContain) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CONTAIN,
                                       newContain);
    }

    public void removeContain(Tasks oldContain) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CONTAIN,
                                          oldContain);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Contain_By
     */
     
    public Collection<? extends Projects> getContain_By() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CONTAIN_BY,
                                               DefaultProjects.class);
    }

    public boolean hasContain_By() {
	   return !getContain_By().isEmpty();
    }

    public void addContain_By(Projects newContain_By) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CONTAIN_BY,
                                       newContain_By);
    }

    public void removeContain_By(Projects oldContain_By) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CONTAIN_BY,
                                          oldContain_By);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate
     */
     
    public Collection<? extends Applications> getGenerate() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_GENERATE,
                                               DefaultApplications.class);
    }

    public boolean hasGenerate() {
	   return !getGenerate().isEmpty();
    }

    public void addGenerate(Applications newGenerate) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_GENERATE,
                                       newGenerate);
    }

    public void removeGenerate(Applications oldGenerate) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_GENERATE,
                                          oldGenerate);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Input_for
     */
     
    public Collection<? extends WorkOrders> getInput_for() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                               DefaultWorkOrders.class);
    }

    public boolean hasInput_for() {
	   return !getInput_for().isEmpty();
    }

    public void addInput_for(WorkOrders newInput_for) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                       newInput_for);
    }

    public void removeInput_for(WorkOrders oldInput_for) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                          oldInput_for);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modified_By
     */
     
    public Collection<? extends Changes> getModified_By() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                               DefaultChanges.class);
    }

    public boolean hasModified_By() {
	   return !getModified_By().isEmpty();
    }

    public void addModified_By(Changes newModified_By) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                       newModified_By);
    }

    public void removeModified_By(Changes oldModified_By) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                          oldModified_By);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support
     */
     
    public Collection<? extends Applications> getSupport() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                               DefaultApplications.class);
    }

    public boolean hasSupport() {
	   return !getSupport().isEmpty();
    }

    public void addSupport(Applications newSupport) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                       newSupport);
    }

    public void removeSupport(Applications oldSupport) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                          oldSupport);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support_By
     */
     
    public Collection<? extends Analyst> getSupport_By() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                               DefaultAnalyst.class);
    }

    public boolean hasSupport_By() {
	   return !getSupport_By().isEmpty();
    }

    public void addSupport_By(Analyst newSupport_By) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                       newSupport_By);
    }

    public void removeSupport_By(Analyst oldSupport_By) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                          oldSupport_By);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ApplicationName
     */
     
    public Collection<? extends String> getApplicationName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, String.class);
    }

    public boolean hasApplicationName() {
		return !getApplicationName().isEmpty();
    }

    public void addApplicationName(String newApplicationName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, newApplicationName);
    }

    public void removeApplicationName(String oldApplicationName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, oldApplicationName);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Description
     */
     
    public Collection<? extends String> getDescription() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, String.class);
    }

    public boolean hasDescription() {
		return !getDescription().isEmpty();
    }

    public void addDescription(String newDescription) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, newDescription);
    }

    public void removeDescription(String oldDescription) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, oldDescription);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Id
     */
     
    public Collection<? extends Integer> getId() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, Integer.class);
    }

    public boolean hasId() {
		return !getId().isEmpty();
    }

    public void addId(Integer newId) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, newId);
    }

    public void removeId(Integer oldId) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, oldId);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectFinishDate
     */
     
    public Collection<? extends XMLGregorianCalendar> getProjectFinishDate() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTFINISHDATE, XMLGregorianCalendar.class);
    }

    public boolean hasProjectFinishDate() {
		return !getProjectFinishDate().isEmpty();
    }

    public void addProjectFinishDate(XMLGregorianCalendar newProjectFinishDate) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTFINISHDATE, newProjectFinishDate);
    }

    public void removeProjectFinishDate(XMLGregorianCalendar oldProjectFinishDate) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTFINISHDATE, oldProjectFinishDate);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectId
     */
     
    public Collection<? extends Integer> getProjectId() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTID, Integer.class);
    }

    public boolean hasProjectId() {
		return !getProjectId().isEmpty();
    }

    public void addProjectId(Integer newProjectId) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTID, newProjectId);
    }

    public void removeProjectId(Integer oldProjectId) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTID, oldProjectId);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectName
     */
     
    public Collection<? extends String> getProjectName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTNAME, String.class);
    }

    public boolean hasProjectName() {
		return !getProjectName().isEmpty();
    }

    public void addProjectName(String newProjectName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTNAME, newProjectName);
    }

    public void removeProjectName(String oldProjectName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTNAME, oldProjectName);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectOwnerName
     */
     
    public Collection<? extends String> getProjectOwnerName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTOWNERNAME, String.class);
    }

    public boolean hasProjectOwnerName() {
		return !getProjectOwnerName().isEmpty();
    }

    public void addProjectOwnerName(String newProjectOwnerName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTOWNERNAME, newProjectOwnerName);
    }

    public void removeProjectOwnerName(String oldProjectOwnerName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTOWNERNAME, oldProjectOwnerName);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectRemmainingTime
     */
     
    public Collection<? extends Object> getProjectRemmainingTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTREMMAININGTIME, Object.class);
    }

    public boolean hasProjectRemmainingTime() {
		return !getProjectRemmainingTime().isEmpty();
    }

    public void addProjectRemmainingTime(Object newProjectRemmainingTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTREMMAININGTIME, newProjectRemmainingTime);
    }

    public void removeProjectRemmainingTime(Object oldProjectRemmainingTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTREMMAININGTIME, oldProjectRemmainingTime);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectStartDate
     */
     
    public Collection<? extends XMLGregorianCalendar> getProjectStartDate() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTSTARTDATE, XMLGregorianCalendar.class);
    }

    public boolean hasProjectStartDate() {
		return !getProjectStartDate().isEmpty();
    }

    public void addProjectStartDate(XMLGregorianCalendar newProjectStartDate) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTSTARTDATE, newProjectStartDate);
    }

    public void removeProjectStartDate(XMLGregorianCalendar oldProjectStartDate) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTSTARTDATE, oldProjectStartDate);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectState
     */
     
    public Collection<? extends String> getProjectState() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTSTATE, String.class);
    }

    public boolean hasProjectState() {
		return !getProjectState().isEmpty();
    }

    public void addProjectState(String newProjectState) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTSTATE, newProjectState);
    }

    public void removeProjectState(String oldProjectState) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTSTATE, oldProjectState);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ProjectType
     */
     
    public Collection<? extends String> getProjectType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTTYPE, String.class);
    }

    public boolean hasProjectType() {
		return !getProjectType().isEmpty();
    }

    public void addProjectType(String newProjectType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTTYPE, newProjectType);
    }

    public void removeProjectType(String oldProjectType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PROJECTTYPE, oldProjectType);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#State
     */
     
    public Collection<? extends Boolean> getState() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, Boolean.class);
    }

    public boolean hasState() {
		return !getState().isEmpty();
    }

    public void addState(Boolean newState) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, newState);
    }

    public void removeState(Boolean oldState) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, oldState);
    }


}
