package Projects.impl;

import Projects.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultIncidents <br>
 * @version generated on Mon Dec 04 20:34:44 COT 2017 by alvarfr
 */
public class DefaultIncidents extends WrappedIndividualImpl implements Incidents {

    public DefaultIncidents(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate
     */
     
    public Collection<? extends Applications> getGenerate() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_GENERATE,
                                               DefaultApplications.class);
    }

    public boolean hasGenerate() {
	   return !getGenerate().isEmpty();
    }

    public void addGenerate(Applications newGenerate) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_GENERATE,
                                       newGenerate);
    }

    public void removeGenerate(Applications oldGenerate) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_GENERATE,
                                          oldGenerate);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Generate_In
     */
     
    public Collection<? extends Applications> getGenerate_In() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_GENERATE_IN,
                                               DefaultApplications.class);
    }

    public boolean hasGenerate_In() {
	   return !getGenerate_In().isEmpty();
    }

    public void addGenerate_In(Applications newGenerate_In) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_GENERATE_IN,
                                       newGenerate_In);
    }

    public void removeGenerate_In(Applications oldGenerate_In) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_GENERATE_IN,
                                          oldGenerate_In);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Input_for
     */
     
    public Collection<? extends WorkOrders> getInput_for() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                               DefaultWorkOrders.class);
    }

    public boolean hasInput_for() {
	   return !getInput_for().isEmpty();
    }

    public void addInput_for(WorkOrders newInput_for) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                       newInput_for);
    }

    public void removeInput_for(WorkOrders oldInput_for) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INPUT_FOR,
                                          oldInput_for);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Modified_By
     */
     
    public Collection<? extends Changes> getModified_By() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                               DefaultChanges.class);
    }

    public boolean hasModified_By() {
	   return !getModified_By().isEmpty();
    }

    public void addModified_By(Changes newModified_By) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                       newModified_By);
    }

    public void removeModified_By(Changes oldModified_By) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_MODIFIED_BY,
                                          oldModified_By);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support
     */
     
    public Collection<? extends Applications> getSupport() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                               DefaultApplications.class);
    }

    public boolean hasSupport() {
	   return !getSupport().isEmpty();
    }

    public void addSupport(Applications newSupport) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                       newSupport);
    }

    public void removeSupport(Applications oldSupport) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUPPORT,
                                          oldSupport);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Support_By
     */
     
    public Collection<? extends Analyst> getSupport_By() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                               DefaultAnalyst.class);
    }

    public boolean hasSupport_By() {
	   return !getSupport_By().isEmpty();
    }

    public void addSupport_By(Analyst newSupport_By) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                       newSupport_By);
    }

    public void removeSupport_By(Analyst oldSupport_By) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUPPORT_BY,
                                          oldSupport_By);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#ApplicationName
     */
     
    public Collection<? extends String> getApplicationName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, String.class);
    }

    public boolean hasApplicationName() {
		return !getApplicationName().isEmpty();
    }

    public void addApplicationName(String newApplicationName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, newApplicationName);
    }

    public void removeApplicationName(String oldApplicationName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_APPLICATIONNAME, oldApplicationName);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Description
     */
     
    public Collection<? extends String> getDescription() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, String.class);
    }

    public boolean hasDescription() {
		return !getDescription().isEmpty();
    }

    public void addDescription(String newDescription) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, newDescription);
    }

    public void removeDescription(String oldDescription) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DESCRIPTION, oldDescription);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#Id
     */
     
    public Collection<? extends Integer> getId() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, Integer.class);
    }

    public boolean hasId() {
		return !getId().isEmpty();
    }

    public void addId(Integer newId) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, newId);
    }

    public void removeId(Integer oldId) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, oldId);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentCreationDate
     */
     
    public Collection<? extends XMLGregorianCalendar> getIncidentCreationDate() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTCREATIONDATE, XMLGregorianCalendar.class);
    }

    public boolean hasIncidentCreationDate() {
		return !getIncidentCreationDate().isEmpty();
    }

    public void addIncidentCreationDate(XMLGregorianCalendar newIncidentCreationDate) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTCREATIONDATE, newIncidentCreationDate);
    }

    public void removeIncidentCreationDate(XMLGregorianCalendar oldIncidentCreationDate) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTCREATIONDATE, oldIncidentCreationDate);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentId
     */
     
    public Collection<? extends Integer> getIncidentId() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTID, Integer.class);
    }

    public boolean hasIncidentId() {
		return !getIncidentId().isEmpty();
    }

    public void addIncidentId(Integer newIncidentId) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTID, newIncidentId);
    }

    public void removeIncidentId(Integer oldIncidentId) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTID, oldIncidentId);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentPriority
     */
     
    public Collection<? extends String> getIncidentPriority() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTPRIORITY, String.class);
    }

    public boolean hasIncidentPriority() {
		return !getIncidentPriority().isEmpty();
    }

    public void addIncidentPriority(String newIncidentPriority) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTPRIORITY, newIncidentPriority);
    }

    public void removeIncidentPriority(String oldIncidentPriority) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTPRIORITY, oldIncidentPriority);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentResolutionDate
     */
     
    public Collection<? extends XMLGregorianCalendar> getIncidentResolutionDate() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTRESOLUTIONDATE, XMLGregorianCalendar.class);
    }

    public boolean hasIncidentResolutionDate() {
		return !getIncidentResolutionDate().isEmpty();
    }

    public void addIncidentResolutionDate(XMLGregorianCalendar newIncidentResolutionDate) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTRESOLUTIONDATE, newIncidentResolutionDate);
    }

    public void removeIncidentResolutionDate(XMLGregorianCalendar oldIncidentResolutionDate) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTRESOLUTIONDATE, oldIncidentResolutionDate);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentState
     */
     
    public Collection<? extends String> getIncidentState() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTSTATE, String.class);
    }

    public boolean hasIncidentState() {
		return !getIncidentState().isEmpty();
    }

    public void addIncidentState(String newIncidentState) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTSTATE, newIncidentState);
    }

    public void removeIncidentState(String oldIncidentState) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTSTATE, oldIncidentState);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#IncidentSummary
     */
     
    public Collection<? extends String> getIncidentSummary() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTSUMMARY, String.class);
    }

    public boolean hasIncidentSummary() {
		return !getIncidentSummary().isEmpty();
    }

    public void addIncidentSummary(String newIncidentSummary) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTSUMMARY, newIncidentSummary);
    }

    public void removeIncidentSummary(String oldIncidentSummary) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INCIDENTSUMMARY, oldIncidentSummary);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/alvarfr/ontologies/2017/11/untitled-ontology-6#State
     */
     
    public Collection<? extends Boolean> getState() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, Boolean.class);
    }

    public boolean hasState() {
		return !getState().isEmpty();
    }

    public void addState(Boolean newState) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, newState);
    }

    public void removeState(Boolean oldState) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STATE, oldState);
    }


}
